apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gllqblua4-go-gitops
  description: This is GitOps manifest for gllqblua4-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gllqblua4-go
    backstage.io/kubernetes-id: gllqblua4-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gllqblua4-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gllqblua4-go
